hw10/hw10/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotes.urls")),
    path("users/", include("users.urls"))
]

hw10/quotes/urls.py
from django.urls import path
from . import views

app_name="quotes"

urlpatterns = [
    path("", views.main, name="root"),
    path("<int:page>", views.main, name="root_paginate"),
    path('author/<int:author_id>', views.about, name="about"),
    path('add_author/', views.add_author, name='add_author'),
    path('add_quote/', views.add_quote, name='add_quote'),
    path('tag/<str:tag_name>/', views.tag_quotes, name='tag-quotes'),
]

hw10/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
]

hw10/quotes/models.py
from django.db import models

# Create your models here.
class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.fullname
    
class Tag(models.Model):
    name = models.CharField(max_length=50, null = False, unique=True)

    def __str__(self):
        return self.name

class Quote(models.Model):
    quote =models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

hw10/users/models.py
from django.db import models

# Create your models here.

hw10/quotes/forms.py
from django import forms
from .models import Author,Quote

class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']

class QuoteForm(forms.ModelForm):
    class Meta:
        model = Quote
        fields = ['quote', 'tags', 'author']

hw10/users/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from django.forms import CharField, TextInput, PasswordInput


class RegisterForm(UserCreationForm):
    username = CharField(max_length=100, required=True, widget=TextInput(attrs={"class": "form-control"}))
    password1 = CharField(max_length=30, min_length=8, required=True, widget=PasswordInput(attrs={"class": "form-control"}))
    password2 = CharField(max_length=30, min_length=8, required=True, widget=PasswordInput(attrs={"class": "form-control"}))


    class Meta:
        model = User
        fields = ("username", 'password1', 'password2')




class LoginForm(AuthenticationForm):
    username = CharField(max_length=100, required=True, widget=TextInput(attrs={"class": "form-control"}))
    password = CharField(max_length=30, min_length=8, required=True, widget=PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ("username", 'password')

hw10/quotes/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count


from .forms import AuthorForm, QuoteForm
from quotes.models import Quote, Tag, Author


# Create your views here.
# from .utils import get_mongodb

# # def main(request):
# def main(request, page=1):
#     db = get_mongodb()
#     quotes = db.quotes.find()
#     per_page = 5
#     paginator = Paginator(list(quotes), per_page)
#     quotes_on_page = paginator.page(page)
#     return render(request, 'quotes/index.html', context={'quotes': quotes_on_page})
    # return render(request, 'quotes/index.html', context={})



def main(request, page=1):
    quotes = Quote.objects.all()
    per_page = 5 #qutes per page
    paginator = Paginator(list(quotes), per_page) 
    quotes_on_page = paginator.page(page)

    top_tags = Tag.objects.annotate(tag_count=Count('quote')).order_by('-tag_count')[:10]

    return render(request, "quotes/index.html", context={'quotes': quotes_on_page, 'top_tags': top_tags})

def about(request, author_id):
    author = get_object_or_404(Author, pk=author_id)
    context = {
        'fullname': author.fullname,
        'born_date': author.born_date,
        'born_location': author.born_location,
        'description': author.description,
    }
    return render(request, 'quotes/about.html', context)


@login_required
def add_author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            new_author = form.save()
        
            return redirect("quotes:about", author_id=new_author.id)

    else:
        form = AuthorForm()
    return render(request, 'quotes/add_author.html', {'form': form})

@login_required
def add_quote(request):
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            quote = form.save()
            return render(request, "quotes/view_quote.html", context={'quote': quote}) 
 
    else:
        form = QuoteForm()
    
    return render(request, 'quotes/add_quote.html', {'form': form})

def tag_quotes(request, tag_name):
    tag = get_object_or_404(Tag, name=tag_name)
    quotes = Quote.objects.filter(tags=tag)
    paginator = Paginator(quotes, 10)

    page = request.GET.get('page')
    try:
        quotes = paginator.page(page)
    except PageNotAnInteger:
        quotes = paginator.page(1)
    except EmptyPage:
        quotes = paginator.page(paginator.num_pages)

    context = {
        'tag': tag,
        'quotes': quotes,
    }

    return render(request, 'quotes/tag_quotes.html', context)

hw10/users/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect

from .forms import RegisterForm,LoginForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required

def signupuser(request):
    if request.user.is_authenticated:
        return redirect(to='quotes:root')

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes:root')
        else:
            return render(request, 'users/signup.html', context={"form": form})

    return render(request, 'users/signup.html', context={"form": RegisterForm()})

def loginuser(request):
    if request.user.is_authenticated:
        return redirect(to='quotes:root')

    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is None:
            messages.error(request, 'Username or password didn\'t match')
            return redirect(to='users:login')

        login(request, user)
        return redirect(to='quotes:root')

    return render(request, 'users/login.html', context={"form": LoginForm()})

@login_required
def logoutuser(request):
    logout(request)
    return redirect(to='quotes:root')

hw10/quotes/templates/quotes/about.html
{% extends 'quotes/base.html' %}

{% block content %}
<head>
    <title>About Author</title>
</head>
    <div class="container">
        <h2>Author</h2>
        <p class="quote">{{ fullname }}</p>
        <h2>Date of birth</h2>
        <p class="quote">{{ born_date }}</p>
        <h2>Place of birth</h2>
        <p class="quote">{{ born_location }}</p>
        <h2>About the Author</h2>
        <p class="quote">{{ description }}</p>
    </div>
</body>
{% endblock %}

hw10/quotes/templates/quotes/add_author.html
{% extends 'quotes/base.html' %}
{% block content %}
<h2>Add author</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-primary" type="submit">Add author</button>
</form>
{% endblock %}

hw10/quotes/templates/quotes/add_quote.html
{% extends "quotes/base.html" %}

{% block content %}
  <h2>Add quote</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-primary" type="submit">Add quote</button>
  </form>
{% endblock %}

hw10/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    {% load static %}

    <link rel="stylesheet" href="{% static 'quotes/style.css' %}" />

    <title>Homework - copy "Quotes to scrape"</title>
  </head>
  <body>
    <div class="container">
      <div class="row header-box pt-3 mb-3">
        <div class="col-md-8">
          <h1>
            <a href="/" style="text-decoration: none">Quotes to Scrape</a>
          </h1>
        </div>
        <div class="col-md-4">
          
          {% if user.is_authenticated %}
          
          <a href="{% url 'users:logout' %}" class="btn btn-primary">Logout</a>
          <a href="{% url 'quotes:add_author' %}" class="btn btn-primary">Add author</a>
          <a href="{% url 'quotes:add_quote' %}" class="btn btn-primary">Add quote</a>

          {% else %}
          
          <a href="{% url 'users:login' %}" class="btn btn-primary">Login</a>
          <a href="{% url 'users:signup' %}" class="btn btn-primary">SignUp</a>
          
          {% endif %}

        </div>
      </div>

      {% block content %} {% endblock%}
      
    </div>
  </body>
</html>

hw10/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}
<div class="row">
    <div class="col-md-10">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{quote.quote}}
            </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags.all %}
                <a class="tag" href="{% url 'quotes:tag-quotes' tag.name %}">{{tag.name}}</a>
                {% endfor %}
            </div>
            <span>
                by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
                <a href="{% url 'quotes:about' quote.author_id %}">(about)</a>
            </span>
        </div>
        {% endfor %}
        <nav>
            <ul class="pager">
                <li class="previous">
                    <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                       href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                        <span aria-hidden="true">←</span>Previous
                    </a>
                </li>
                <li class="next">
                    <a class="{% if not quotes.has_next %} disabled {% endif %}"
                       href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                        Next<span aria-hidden="true">→</span>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
    <div class="col-md-2 tags-box">
        <h2>Top Ten tags</h2>
        {% for tag in top_tags %}
        <div class="tag-item mb-2">
            <a class="tag" style="font-size: 28px" href="{% url 'quotes:tag-quotes' tag.name %}">{{ tag.name }}</a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

hw10/quotes/templates/quotes/view_quote.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}
     
<div class="row">
    <div class="col-md-8 mb-3">
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{quote.quote}}
            </span>
                <div class="tags">
                    Tags:
                    {% for tag in quote.tags.all %}
                    <a class="tag" href="/tag/{{tag}}">{{tag.name}}</a>
                    {% endfor %}    
                </div>

            <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
        <a href="/author/{{quote.author_id}}">(about)</a>
        </span> 


        </div>

</div>
{% endblock %}

hw10/users/templates/users/login.html
{% extends "quotes/base.html" %}

{% block content %}

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <div class="container">
        <div class="row header-box pt-3 mb-3">
            <label> Username:
                {{ form.username }}
            </label>
        </div>

        <div class="row header-box pt-3 mb-3">
            <label>Password:
                {{ form.password }}
            </label>
        </div>

        <div class="grid">
            <button class="btn btn-primary" type="submit">Submit</button>
            <button class="btn btn-secondary" type="reset" class="secondary">Reset</button>
        </div>
    </div>
</form>

{% endblock %}

hw10/users/templates/users/logout.html
{% extends "quotes/base.html" %} {% block content %}

<h1>Log Out</h1>


{% endblock %}

hw10/users/templates/users/signup.html
{% extends "quotes/base.html" %} {% block content %}

<h1>SignUp</h1>


<form method="post">
  {% csrf_token %}
    <div class="form-row">
        <div class="mb-3">
        <label class="form-label">Username</label>
            {{form.username}}
        </div>
        <span>{{form.errors.username}}</span>
    </div>

    <div class="form-row">
        <div class="mb-3">
        <label class="form-label">First Name</label>
            {{form.firstname}}
        </div>
        <span>{{form.errors.firstname}}</span>
    </div>

    <div class="form-row">
        <div class="mb-3">
        <label class="form-label">Last Name</label>
            {{form.lastname}}
        </div>
        <span>{{form.errors.lastname}}</span>
    </div>

    <div class="form-row">
        <div class="mb-3">
        <label class="form-label">Email</label>
            {{form.email}}
        </div>
        <span>{{form.errors.email}}</span>
    </div>

    <div class="form-row">
        <div class="mb-3">
        <label class="form-label">Password</label>
            {{form.password1}}
        </div>
        <span>{{form.errors.password1}}</span>
    </div>

    <div class="form-row">
        <div class="mb-3">
        <label class="form-label">Confirm password</label>
            {{form.password2}}
        </div>
        <span>{{form.errors.password2}}</span>
    </div>

  <button type="submit" class="btn btn-primary">Sign Up</button>
</form>

{% endblock %}